---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansi
  gather_facts: no
  tasks:
    - name: timezone chnaging
      become: yes
      shell : "sudo timedatectl set-timezone Africa/Johannesburg"
      
    - name: check the current time
      
      shell : "sudo timedatectl"
